Repository billyjojojobulido/hotaru, pull requests merged in 2024-11, with the labels that each got.

#3 - setup environment #2
  requirements.txt
Labels: enhancement

#7 F audio manager
  audio_manager/__init__.py
  audio_manager/utils.py
  main.py
  resources/test/test_audio_sample.mp3
Labels: enhancement

#9 F issue 8
  audio_manager/utils.py
  classes/__init__.py
  main.py
  resources/audio_info.py
  resources/test/audio_config.json
Labels: enhancement

#11 F issue 10
  audio_manager/utils.py
Labels: enhancement

#13 Update README.md
  README.md
Labels: documentation, enhancement

#14 Create audio_info.py in classes module
  classes/audio_info.py
Labels: enhancement

#15 Delete resources/audio_info.py
  resources/audio_info.py
Labels: enhancement

#18 - added licence badge #4 fixed
  README.md
Labels: enhancement

#21 F issue 20
  main.py
Labels: bug

#24 Test breakpoint
  audio_manager/utils.py
  main.py
  resources/audio_config.json
Labels: bug

#26 Fix issue 25
  resources/audio_config.json
Labels: bug

#28 Update README.md & added terms and conditions
  README.md
Labels: documentation, enhancement

#29 Fix issue 27
  audio_manager/utils.py
  main.py
  resources/audio_config.json
Labels: bug, enhancement

#30 F audio loop
  audio_manager/utils.py
  models/__init__.py
  models/audio_info.py
  models/audio_node.py
Labels: enhancement

#31 F audio loop
  audio_manager/utils.py
  main.py
Labels: enhancement

#32 - finished the audio loop data structure && TODO UI
  main.py
Labels: enhancement

#33 Update README.md
  README.md
Labels: documentation, enhancement

#40 F UI scaffold
  app/__init__.py
  app/window.py
  main.py
Labels: enhancement

#43 F issue 37
  app/window.py
Labels: enhancement

#44 F issue 37
  app/window.py
Labels: enhancement

#46 Update audio_config.json
  resources/audio_config.json
Labels: enhancement

#50 - issue #48 fixed
  resources/audio_config.json
Labels: bug

#51 F issue 45
  app/window.py
Labels: enhancement

#53 Update audio_config.json
  resources/audio_config.json
Labels: enhancement

#55 - fixed issue #54
  resources/audio_config.json
Labels: bug

#58 F btn
  app/window.py
Labels: enhancement

#60 - temp save
  app/window.py
Labels: enhancement, wontfix

#64 F issue 59
  app/window_01.py
  requirements.txt
Labels: enhancement

#69 - able to play audio using UI now
  app/window_01.py
Labels: enhancement

#71 F issue 70
  app/window_01.py
  audio_manager/utils.py
Labels: enhancement

#78 Fix config
  resources/audio_config.json
Labels: bug

#80 Update audio_config.json
  resources/audio_config.json
Labels: enhancement

#84 F issue 83
  app/window_01.py
  models/audio_node.py
Labels: enhancement

#85 - fixed audio sample 70170 & 70171
  resources/audio_config.json
Labels: enhancement

#86 Update audio_config.json
  resources/audio_config.json
Labels: enhancement

#89 Update README.md - more badges
  README.md
Labels: enhancement

#90 Update audio_config.json
  resources/audio_config.json
Labels: enhancement

#91 Fix config
  resources/audio_config.json
Labels: enhancement

#96 F doc contribute
  CONTRIBUTING.md
Labels: documentation, enhancement

#98 Update README.md
  README.md
Labels: documentation, enhancement

#99 Update CONTRIBUTING.md :: typo fixed
  CONTRIBUTING.md
Labels: bug, documentation, enhancement

#100 Update audio_config.json
  resources/audio_config.json
Labels: enhancement

#101 F issue 94
  CHANGELOG.md
Labels: documentation, enhancement

#102 F issue 95
  CODE_OF_CONDUCT.md
Labels: documentation, enhancement

#103 Update README.md
  README.md
Labels: documentation, enhancement

#107 F set panel
  app/window_01.py
Labels: enhancement

#108 - changelog
  CHANGELOG.md
Labels: documentation, enhancement

#109 F progress bar
  README.md
  app/window_01.py
Labels: documentation, enhancement

#111 F console log
  app/window_01.py
  component/__init__.py
  component/console.py
Labels: enhancement

#114 F console log
  app/window_01.py
  component/console.py
  models/audio_node.py
Labels: bug, enhancement

#115 - fixed issue #112 and #97
  app/window_01.py
Labels: bug, enhancement

#116 F console log
  app/window_01.py
  component/console.py
  main.py
Labels: enhancement

#118 Update README.md
  README.md
Labels: documentation, enhancement

#120 F refine
  CHANGELOG.md
  app/__init__.py
  app/main_window.py
  app/window.py
  app/window_01.py
  app/window_02.py
  audio_manager/__init__.py
  component/__init__.py
  component/audio_panel.py
  component/controller_panel.py
  component/setting_panel.py
  main.py
Labels: enhancement
